config/api/urls.py
from django.urls import path
from .views import (books, BookDetail, orders, order_create, order_delete, register )
app_name = "api"

urlpatterns = [
    path('', books, name="books"),
    path('<int:pk>', BookDetail.as_view(), name="book"),\

    path('orders/', orders, name="orders"),
    path('order/add/', order_create, name="order-add"),
    path('order/delete/<int:pk>', order_delete, name="order-delete"),

    path('register/', register, name='user-register'),

    
]

config/book/urls.py
from operator import imod
from django.urls import path
from .views import Home, book_detail
from django.conf import settings
from django.conf.urls.static import static

app_name = 'book'
urlpatterns = [
    path('', Home.as_view(), name='books'),
    path('book/<int:pk>', book_detail, name='book-detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/config/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls', namespace='book')),
    path('order/', include('order.urls', namespace='order')),
    path('api/', include('api.urls', namespace="api")),
    #swagger path
    path('swagger', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

]

config/order/urls.py
from django.urls import path
from .views import orders_list, order_delete, order_create

app_name = 'order'
urlpatterns = [
    path('orders', orders_list, name='my-orders'),
    path('order_create/<int:pk>', order_create, name='create-orders'),
    path('order_delete/<int:pk>', order_delete, name='del-orders'),

]

config/order/models.py
from django.db import models
from django.contrib.auth import get_user_model
from book.models import Book
from django.urls import reverse

class Order(models.Model):
    USER = get_user_model()
    user = models.ForeignKey(USER, on_delete=models.CASCADE, related_name='user_order', verbose_name='نام یوزر')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='book_order', verbose_name='نام کتاب')
    reserv_date = models.DateTimeField(auto_now_add=True)
    is_reserve = models.BooleanField(default=True)
    
    class Meta:
        ordering = ('reserv_date',)

    def __str__(self):
        return f"{self.book}"

config/order/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Order
from book.models import Book
from django.contrib.auth.decorators import login_required



@login_required
def orders_list(request):
    """
        List of all books that the user has requested
    """
    orders = Order.objects.filter(user=request.user, is_reserve=True)
    context = {
        'orders':orders
    }
    return render(request, 'order/orders.html', context)



@login_required
def order_delete(request, pk):
    """
        Delete one of the books that the user ordered
    """
    order = get_object_or_404(Order, user=request.user, pk=pk)
    book = get_object_or_404(Book, pk=order.book.id)
    book.reserve=False
    book.save()
    order.is_reserve=False
    order.save()
    return redirect('order:my-orders')



@login_required
def order_create(request, pk):
    """
        Create a request and order a book from the list of books that do not appear
    """
    book = get_object_or_404(Book, pk=pk)
    if book.reserve:
        return redirect('order:my-orders')
        
    order = Order.objects.create(user=request.user,book=book)
    order.save()
    book.reserve=True
    book.save()
    return redirect('order:my-orders')

config/order/templates/order/orders.html
{% extends 'base.html' %}
{% load static %}

{% block header_tag %}
    <link rel="stylesheet" href="{% static 'order/css/orders.css' %}">
{% endblock header_tag %}

{% block content %}
<div class="status-user-widget" id="order-tracking-info">
    <table>                              
      <thead class="header-order-tracking">
        <tr>
            <th>
              <div class="test">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" style="width: 20px;">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                  </svg>
                  حذف
                </div>
              </th>
              
              <th>
                <div class="test">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" style="width: 20px">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                  </svg>
                  تاریخ                  
              </div>
            </th>

            <th>
              <div class="test">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" style="width: 20px">                  
                  <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
                </svg>
                کتاب
              </div>
            </th>
        </tr>
      </thead>
      <tbody class="body-order-tracking">
        {% for order in orders %}
          <tr>
            {%if order.is_reserve %}
            <td><a id="delete-book" href="{% url 'order:del-orders' order.id%}">حذف</a></td>
              <td>{{order.reserv_date}}</td>              
              <td><a href="{% url 'book:book-detail' order.book.id%}">{{order.book.title}}</a></td>
            {% endif %}
            {% empty %}
              هیچ کتابی رزرو نکرده اید 
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock content %}