config/api/urls.py
from django.urls import path
from .views import (books, BookDetail, orders, order_create, order_delete, register )
app_name = "api"

urlpatterns = [
    path('', books, name="books"),
    path('<int:pk>', BookDetail.as_view(), name="book"),\

    path('orders/', orders, name="orders"),
    path('order/add/', order_create, name="order-add"),
    path('order/delete/<int:pk>', order_delete, name="order-delete"),

    path('register/', register, name='user-register'),

    
]

config/book/urls.py
from operator import imod
from django.urls import path
from .views import Home, book_detail
from django.conf import settings
from django.conf.urls.static import static

app_name = 'book'
urlpatterns = [
    path('', Home.as_view(), name='books'),
    path('book/<int:pk>', book_detail, name='book-detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/config/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls', namespace='book')),
    path('order/', include('order.urls', namespace='order')),
    path('api/', include('api.urls', namespace="api")),
    #swagger path
    path('swagger', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

]

config/order/urls.py
from django.urls import path
from .views import orders_list, order_delete, order_create

app_name = 'order'
urlpatterns = [
    path('orders', orders_list, name='my-orders'),
    path('order_create/<int:pk>', order_create, name='create-orders'),
    path('order_delete/<int:pk>', order_delete, name='del-orders'),

]

config/book/models.py
from django.db import models
from django.urls import reverse



class Genre(models.Model):
    title = models.CharField(max_length=70)
    slug = models.SlugField(unique=True, verbose_name='آدرس')

    def __str__(self):
        return self.title    


class Author(models.Model):
    name = models.CharField(max_length=30, verbose_name="نام نویسنده" )

    def __str__(self):
        return self.name    


class Book(models.Model):
    title = models.CharField(max_length=70, verbose_name="نام کتاب")
    slug = models.SlugField(unique=True, verbose_name='آدرس')
    athore = models.ForeignKey(
        Author, 
        on_delete=models.CASCADE, 
        verbose_name="نویسنده کتاب", 
        related_name="book_athore"
        )
    description = models.TextField(verbose_name="توضیحات کتاب")
    photo = models.ImageField(upload_to='images/book/%Y/%m/%d/', verbose_name="عکس محصول")
    release_date = models.IntegerField(verbose_name="تاریخ انتشار کتاب")
    reserve = models.BooleanField(default=False, verbose_name="رزرو شده ؟")
    genre = models.ManyToManyField(Genre, related_name='book_genre', verbose_name="ژانر کتاب")
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book:book-detail',args=[self.pk])
    

config/book/views.py
from audioop import reverse
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from .models import Book


class Home(ListView):
    """
        List of all books available on the website.
    """
    template_name = 'book/books.html'
    context_object_name = 'books'
    ordering =['-title']
    model = Book


def book_detail(request, pk:int):
    """
        Display of a special book with ID
    """
    book = get_object_or_404(Book,pk=pk)
    context = {
        'book':book
    }
    return render(request, 'book/book-detail.html', context)

config/book/templates/book/book-detail.html
{% extends 'base.html' %}
{% load static %}

{% block header_tag %}
    <link rel="stylesheet" href="{% static 'book/css/book-detail.css' %}">
{% endblock header_tag %}

{% block content %}
    <section class="sec-first">
        <div class="sec-first-container">
            <div class="img-detail">
                <div class="img-back"></div>
                <img src="{{ book.photo.url }}">
            </div>
            <div class="container-detail">
                <span></span>
                <h1>{{book.title}}</h1>
                <p style="direction:rtl; padding-right:30px">{{book.description}}</p>

                {% if not book.reserve %}
                    <a href="{% url 'order:create-orders' book.id %}" class="reserve-btn">Reserve</a>
                {% else %}
                  <div class="reserve-book">
                    <h2>این کتاب رزرو شده است</h2>
                  </div>
                {% endif %}

            </div>
        </div>
    </section>
{% endblock %}

config/book/templates/book/books.html
{% extends 'base.html' %}
{% load static %}

{% block header_tag %}
    <link rel="stylesheet" href="{% static 'book/css/books.css' %}">
{% endblock header_tag %}

{% block content %}
<div id="large-th">
    <div class="container">
      <h1 class="book-header"> لیست کتاب ها</h1>
      <br>
      <div id="list-th">
        {% for book in books %}
            <div class="book read">
                <div class="cover">
                    <img src="{{book.photo.url}}">
                </div>
                <div class="description">
                    <p class="title">
                      <span class="title-book">{{book.title}}<br></span>
                      <span class="author">{{book.athore}}</span>
                    </p>
                    <a href="{{ book.get_absolute_url }}" id="show-book">Show Book</a>
                </div>                
            </div>
        {% empty %}
            هیچ کتابی وجود ندارد
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock content %}