config/api/urls.py
from django.urls import path
from .views import (books, BookDetail, orders, order_create, order_delete, register )
app_name = "api"

urlpatterns = [
    path('', books, name="books"),
    path('<int:pk>', BookDetail.as_view(), name="book"),\

    path('orders/', orders, name="orders"),
    path('order/add/', order_create, name="order-add"),
    path('order/delete/<int:pk>', order_delete, name="order-delete"),

    path('register/', register, name='user-register'),

    
]

config/config/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls', namespace='book')),
    path('order/', include('order.urls', namespace='order')),
    path('api/', include('api.urls', namespace="api")),
    #swagger path
    path('swagger', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

]

config/order/urls.py
from django.urls import path
from .views import orders_list, order_delete, order_create

app_name = 'order'
urlpatterns = [
    path('orders', orders_list, name='my-orders'),
    path('order_create/<int:pk>', order_create, name='create-orders'),
    path('order_delete/<int:pk>', order_delete, name='del-orders'),

]

config/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% block header %} {% endblock %}

    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    {% block header_tag %} {% endblock header_tag %}
    <title>Document</title>
</head>

<body>
    <div class="nav-bar">
        <span><h1>کتابخانه</h1></span>
        <ul>
            <li><a class="active" href="{%url 'book:books' %}"> Home </a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'order:my-orders' %}"> My Book </a></li>
            {% endif %}
        </ul>
    </div>
    <div class="card-body">
        {% block content %} {% endblock %}
    </div>

      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    </body>
</html>